export const LIST_ITEM = 'LIST_ITEM';
export const SET_ITEM_STATE_FILTER = 'SET_ITEM_STATE_FILTER';
export const TOGGLE_ITEM_STATUS = 'TOGGLE_ITEM_STATUS';
export const CREDIT_ACCOUNT = 'CREDIT_ACCOUNT';
export const DEBIT_ACCOUNT = 'DEBIT_ACCOUNT';
